### ISSUE TITLE
UnboundLocalError: local variable 'r' referenced before assignment

### ISSUE THREAD

**Issue by hanklogan** [ethanagbaker/SiLiCO#1]
Hi, I'm getting the following error running the simulator, any help would be great!

> /data/Python-3.5.2/python /data/SiLiCO-master/SiLiCO.py -i chr1.fa -m 2000 -s 500 -c 30

Preparing the genome file.
The Scratch dir already exists. Cleaning up...
Done!
Generating a genome index file...
Done!
Generating simulated reads in PacBio mode...
Building threshold dictionaries...
Calculating distribution parameters...
Traceback (most recent call last):
  File "/data/SiLiCO-master/SiLiCO.py", line 166, in <module>
    main(sys.argv[1:])
  File "/data/SiLiCO-master/SiLiCO.py", line 151, in main
    simulateReads(infileName,outfileName,mean,std,desired_cov,trialCount,names, SEQ_MODE)
  File "/data/SiLiCO-master/simulateReads.py", line 92, in simulateReads
    y=getRandomPosition(buf,genomeLength,thresholdDict,names,lengthDict)
  File "/data/SiLiCO-master/getRandomPosition.py", line 23, in getRandomPosition
    if t+buf <= y <= r-buf:
UnboundLocalError: local variable 'r' referenced before assignment

**Comment by ethanagb** [comment]
Looking into this now. Initially I was not able to recreate the issue, but now I think I see what's causing your issue. Going to push a fix shortly.

**Comment by hanklogan** [comment]
Thanks for the quick response! Will keep an eye out for the fix.

**Comment by ethanagb** [comment]
Hello again, I've just pushed an update that I think should address your problem. Also, I highly recommend that you run SiLiCO using Python 2.7, over Python 3, as the porting process is a work in progress. 

A sample run of SiLiCO after the fix:

``` python
python SiLiCO.py  -i ~/testing/maize_genome/genome.fa -c 30 -m 2000 -s 500 --fasta -o ~/testing/

Preparing the genome file.
The Scratch dir already exists. Cleaning up...
Done!
Generating a genome index file...
Done!
Generating simulated reads in PacBio mode...
Building threshold dictionaries...
Calculating distribution parameters...
Completed trial 1 of 1. (100.0%)
Done!
Converting simulated BED files to FASTA files...
Done!
Exiting...
```

This generates the output files (`.bed` and `.fa` in the `-o` directory). 

Let me know if you have any other problems/questions...
