### ISSUE TITLE
SiLiCO generate empty fasta and bed file

### ISSUE THREAD

**Issue by natir** [ethanagbaker/SiLiCO#3]
Hi,

Thanks for your work, but when I run SiLiCO like this : 

```bash
python SiLiCO.py -i ${path to desulfosporosinus_acidiphilus genome in fasta} -o test
```

or like this 

```bash
python SiLiCO.py -i ~/dat/MBRAC-5/genomes/desulfosporosinus_acidiphilus.fasta -o test --fasta
python SiLiCO.py -i ~/dat/MBRAC-5/genomes/desulfosporosinus_acidiphilus.fasta -o test_ -n --fasta -m 100000000000
python3 SiLiCO.py -i ~/dat/MBRAC-5/genomes/desulfosporosinus_acidiphilus.fasta -o test_ -n --fasta -m 100000000000
```

The bed and fasta file is empty.

Link to my test reference genome https://www.ncbi.nlm.nih.gov/assembly/GCF_000255115.2/

Thanks

**Comment by ethanagb** [comment]
Have not taken a look, but one possibility here is that your header line in
the fasta file has extra information. Try changing it to simply >chr1, as
SiLiCO expects headers in this style.

**Comment by natir** [comment]
The header of my fasta sequence is just : 

```
>NC_018068.1
```

**Comment by ethanagb** [comment]
This is likely your problem. SiLiCO expects a chromosomal assembly with
headers of style >chr*. The chr is relevant. I believe this is specified in
the docs.

**Comment by natir** [comment]
Ok when the header of my fasta sequence look like ```>chr*``` SiLiCO generate result thank
